apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}
  namespace: {{.Values.namespace}}
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.namespace}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.namespace}}
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: rabbitmq-secrets
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: main
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30