apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.namespace}}
  name: {{.Values.namespace}}
  namespace: {{.Values.namespace}}
spec:
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{.Values.namespace}}
  type: {{.Values.service.type}}