apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: {{.Values.namespace}}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- end }}
      {{- if and .Values.persistence.enabled .Values.securityContext.initChownEnabled }}
      initContainers:
        - name: n8n-volume-permissions
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - chown -R 1000:1000 {{ .Values.persistence.mountPath }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: n8n-data
              mountPath: {{ .Values.persistence.mountPath }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: "America/New_York"
            - name: GENERIC_TIMEZONE
              value: "America/New_York"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: QUEUE_HEALTH_CHECK_ACTIVE
              value: "true"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: n8n-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
