apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{.Values.service.protocol}}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
