apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: {{ .Values.tailscale.proxyGroupName }}
spec:
  type: ingress
  tags:
    - "tag:k8s"
    - "tag:valheim"
  replicas: {{ .Values.tailscale.proxyReplicas }}
