apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.server.claimName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.server.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.world.claimName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.world.size }}
