namespace: rabbitmq
replicaCount: 1

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: 4.0.5-management

service:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi