apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.namespace}}
  name: {{.Values.namespace}}
  namespace: {{.Values.namespace}}
spec:
  revisionHistoryLimit: 1
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: minio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - args:
            - minio server /data --console-address :9090
          command:
            - /bin/bash
            - -c
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: MINIO_ROOT_USER
                  name: minio-secrets
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: minio-secrets
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: {{.Values.namespace}}
          ports:
            - containerPort: {{.Values.service.apiPort}}
              name: api
              protocol: TCP
            - containerPort: {{.Values.service.consolePort}}
              name: console
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: minio-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc-longhorn