apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: {{.Values.namespace}}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio-kraken.duckdns.org
        - minio-kraken-console.duckdns.org
      secretName: minio-tls
  rules:
    - host: minio-kraken-console.duckdns.org
      http:
        paths:
          - backend:
              service:
                name: minio-svc
                port:
                  number: 9090
            path: /
            pathType: Prefix
    - host: minio-kraken.duckdns.org
      http:
        paths:
          - backend:
              service:
                name: minio-svc
                port:
                  number: 9000
            path: /
            pathType: Prefix