apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-longhorn
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem